//============================================
// Spawning
//============================================
class UaS_WildAssaultPack : IdleDummy {
	override void postbeginplay() {
		super.postbeginplay();

		let Spawned = UaS_AssaultPack(spawn("UaS_AssaultPack", pos, ALLOW_REPLACE));
		Spawned.RandomContents("HDCoreStorageItemList", frandom(0.1, 0.5), false);

		Spawned.vel = vel;
		HDF.TransferSpecials(self, Spawned);

		destroy();
	}
}
